version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: mydockeruser/fullstack-backend:latest
    ports:
      - "8000:80"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    image: mydockeruser/fullstack-frontend:latest
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
