version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mongo
    volumes:
      - ./backend:/var/www/html

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
