name: Fullstack CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. List files for debugging (optional, can remove later)
      - name: List repo files
        run: ls -R Fullstack  

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 4. Build and push Docker images
      - name: Build and push images
        run: |
          cd Fullstack   # folder containing Dockerfiles + docker-compose.yml
          docker compose build
          docker compose push

      # 5. Deploy to server
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/Fullstack/
            docker compose pull
            docker compose up -d --remove-orphans
