name: Docker CI/CD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub (or GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # Build and push frontend image
      - name: Build & push frontend
        run: |
          docker build -f frontend.dockerfile -t mydockeruser/fullstack-frontend:latest .
          docker push mydockeruser/fullstack-frontend:latest

      # Build and push backend image
      - name: Build & push backend
        run: |
          docker build -f backend.dockerfile -t mydockeruser/fullstack-backend:latest .
          docker push mydockeruser/fullstack-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/project
            docker-compose pull
            docker-compose up -d
