name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 4. Build & push frontend image
      - name: Build & push frontend image
        run: |
          docker build \
            --file frontend.dockerfile \
            --tag mydockeruser/fullstack-frontend:latest \
            ./frontend
          docker push mydockeruser/fullstack-frontend:latest

      # 5. Build & push backend image
      - name: Build & push backend image
        run: |
          docker build \
            --file backend.dockerfile \
            --tag mydockeruser/fullstack-backend:latest \
            ./backend
          docker push mydockeruser/fullstack-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 1. Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /path/to/project
            docker-compose pull
            docker-compose up -d --remove-orphans
