name: Docker CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build & push frontend image
        run: |
          docker build -f frontend.dockerfile -t chinuboss/frontend-app:latest .
          docker push chinuboss/frontend-app:latest

      - name: Build & push backend image
        run: |
          docker build -f backend.dockerfile -t chinuboss/backend-app:latest .
          docker push chinuboss/backend-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Stopping old containers..."
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker stop backend-app || true
            docker rm backend-app || true

            echo "Pulling latest images..."
            docker pull chinuboss/frontend-app:latest
            docker pull chinuboss/backend-app:latest

            echo "Running backend container..."
            docker run -d \
              --name backend-app \
              -p 8080:80 \
              chinuboss/backend-app:latest

            echo "Running frontend container..."
            docker run -d \
              --name frontend-app \
              -p 80:80 \
              chinuboss/frontend-app:latest
