name: Docker CI/CD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 3. Build & push frontend image
      - name: Build & push frontend
        run: |
          docker build -f frontend.dockerfile -t mydockeruser/fullstack-frontend:latest ./frontend
          docker push mydockeruser/fullstack-frontend:latest

      # 4. Build & push backend image
      - name: Build & push backend
        run: |
          docker build -f backend.dockerfile -t mydockeruser/fullstack-backend:latest ./backend
          docker push mydockeruser/fullstack-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /path/to/project
            docker-compose pull
            docker-compose up -d
