name: Docker CI/CD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build & push frontend image
        run: |
          docker build -f frontend.dockerfile -t mydockeruser/fullstack-frontend:latest .
          docker push mydockeruser/fullstack-frontend:latest

      - name: Build & push backend image
        run: |
          docker build -f backend.dockerfile -t mydockeruser/fullstack-backend:latest .
          docker push mydockeruser/fullstack-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /path/to/project
            docker-compose pull
            docker-compose up -d --remove-orphans
